In [25]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np
from pandas.io.parsers import read_csv

# model=tf.global_variables_initializer()

model=tf.keras.models.Sequential()

#csv 파일 읽어오기
data=read_csv('user_pattern.csv',sep=',')

#xy 변수에 행렬 형태로 변수 담아옴.
xy=np.array(data,dtype=np.float32)
print(xy)

[[1.00e+00 1.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 2.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 3.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 4.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 5.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 6.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 7.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 1.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 2.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 3.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 4.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 5.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 6.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 7.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 1.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 2.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 3.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 4.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 5.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 6.00e+00 2.70e+02 1.14e+03 1.41e+03]
 [1.00e+00 7.00e+00 2.70e+02 1.14e+03 1.

In [35]:
x_data=xy[:,1:-1]
y_data=xy[:,[-1]]

#값 초기화
X=tf.placeholder(tf.float32, shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])
W=tf.Variable(tf.random_normal([3,1]),name="weight") #가중치
b=tf.Variable(tf.random_normal([1]),name="bias") #바이어스

# 가설을 설정합니다.
hypothesis = tf.matmul(X, W) + b

# model.add(tf.keras.layers.Dense(1, input_dim=4)
# sgd=tf.keras.optimizers.SGD(learning_rate=0.000005)
# model.fit(x_data,y_data,epochs=2000)


# #가설식 새우기. 행열 연산
# @tf.function
# def forward(X):
#     return tf.matmul(X,W)+b



#비용함수 설정
cost=tf.reduce_mean(tf.square(hypothesis-Y))

#최적화 함수 설정(학습률:0.000005) 학습률은 데이터 정제의 정도이나, 유형에 따라 다르게 설정
optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.000005)
train=optimizer.minimize(cost)

#세션값 만들어서 세션에 따라 학습 수행
sess=tf.Session()
sess.run(tf.global_variables_initializer())

#20번마다 진행 상황 확인 위해 진행값 출력
for step in range(90):
    cost_,hypo_,_=sess.run([cost,hypothesis,train], feed_dict={X:x_data, Y:y_data})
    if step%20==0:
        print("#",step,"cost:",cost_)
        print("-끝난시간: ",hypo_[0])


        
#학습된 모델 저장
saver=tf.train.Saver()
save_path=saver.save(sess,",/saved.cpkt")
print("학습된 모델 저장 완료")

# 0 cost: 7724599.5
-끝난시간:  [-1368.3551]
# 20 cost: inf
-끝난시간:  [-3.445127e+25]
# 40 cost: nan
-끝난시간:  [nan]
# 60 cost: nan
-끝난시간:  [nan]
# 80 cost: nan
-끝난시간:  [nan]
학습된 모델 저장 완료
