In [38]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np
from pandas.io.parsers import read_csv

# model=tf.global_variables_initializer()

model=tf.keras.models.Sequential()

#csv 파일 읽어오기
data=read_csv('user_pattern.csv',sep=',')

#xy 변수에 행렬 형태로 변수 담아옴.
xy=np.array(data,dtype=np.float32)
print(xy)

[[   3.    6.  543. 1029.]
 [   3.    4. 1073. 1325.]
 [   3.    7.  548. 1024.]
 ...
 [   3.    5. 1070. 1311.]
 [   3.    2. 1075. 1323.]
 [   3.    4. 1072. 1316.]]


In [41]:
x_data=xy[:,1:-1]
y_data=xy[:,[-1]]

#값 초기화
X=tf.placeholder(np.float32, shape=[None,2])
Y=tf.placeholder(np.float32,shape=[None,1])
W=tf.Variable(tf.random_normal([2,1]),name="weight") #가중치
b=tf.Variable(tf.random_normal([1]),name="bias") #바이어스

# 가설을 설정합니다.
hypothesis = tf.matmul(X, W) + b

# model.add(tf.keras.layers.Dense(1, input_dim=4)
# sgd=tf.keras.optimizers.SGD(learning_rate=0.000005)
# model.fit(x_data,y_data,epochs=2000)


# #가설식 새우기. 행열 연산
# @tf.function
# def forward(X):
#     return tf.matmul(X,W)+b



#비용함수 설정
cost=tf.reduce_mean(tf.square(hypothesis-Y))

#최적화 함수 설정(학습률:0.000005) 학습률은 데이터 정제의 정도이나, 유형에 따라 다르게 설정
optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.000000005)
train=optimizer.minimize(cost)

#세션값 만들어서 세션에 따라 학습 수행
sess=tf.Session()
sess.run(tf.global_variables_initializer())

#20번마다 진행 상황 확인 위해 진행값 출력
for step in range(1000):
    cost_,hypo_,_=sess.run([cost,hypothesis,train], feed_dict={X:x_data, Y:y_data})
    if step%100==0:
        print("#",step,"cost:",cost_)
        print("-끝난시간: ",hypo_[0])

data=((6,540),)
arr=np.array(data,dtype=np.float32)

x_data=arr[0:2]
print(x_data)
dict=sess.run(hypothesis,feed_dict={X:x_data})
print(dict)
        
#학습된 모델 저장
saver=tf.train.Saver()
save_path=saver.save(sess,"./saved_user_3_pattern_model.cpkt")
print("학습된 모델 저장 완료")

# 0 cost: 10099304.0
-끝난시간:  [-1111.6039]
# 100 cost: 1643859.2
-끝난시간:  [-29.284609]
# 200 cost: 292643.8
-끝난시간:  [403.37915]
# 300 cost: 76713.42
-끝난시간:  [576.33997]
# 400 cost: 42206.438
-끝난시간:  [645.4831]
# 500 cost: 36691.688
-끝난시간:  [673.1244]
# 600 cost: 35809.96
-끝난시간:  [684.1757]
# 700 cost: 35668.68
-끝난시간:  [688.5945]
# 800 cost: 35645.684
-끝난시간:  [690.3621]
# 900 cost: 35641.62
-끝난시간:  [691.0702]
[[  6. 540.]]
[[687.48773]]
학습된 모델 저장 완료
